[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.33"
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing config
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

# Remappings for imported libraries
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@aave/contracts/=lib/aave-v3-core/contracts/",
    "@aave/periphery/contracts/=lib/aave-v3-periphery/contracts/", 
    "@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/",
    "@uniswap/v3-core/contracts/=lib/v3-core/contracts/",
]